# Usage: ./RMT release

_default:

    # VCS CONFIG
    vcs: git

    # PREREQUISITES
    prerequisites:
     - working-copy-check
     - tests-check:
          command: bin/phpunit -c app

    # GENERAL CONFIG
    version-generator: simple
    version-persister: "src/Janus/ServiceRegistry/Release/Version/Persister/JanusVersionPersister.php"
    post-release-actions:
      - src/Janus/ServiceRegistry/Release/Action/BuildArchiveAction.php

# BRANCH SPECIFIC CONFIG
#  On master, we override the general config
master:
    version-generator: semantic
    version-persister: vcs-tag
    pre-release-actions:
        changelog-update:          # Update a CHANGELOG file before the release
            file: CHANGES
            format: semantic
        vcs-commit: ~              # Commit the CHANGELOG