# Usage: ./RMT release


_default:

    # VCS CONFIG
    vcs: git

    # PREREQUISITES
    #  Actions executed before any questions get asked to the user.
    #  Custom action can be added by provided a relative path a PHP script. Example:
    #   - relative/path/to/your-own-script.php
    prerequisites:
     - working-copy-check
     - tests-check:
          command: bin/phpunit -c app

    # GENERAL CONFIG
    version-generator: simple
    version-persister: "src/Janus/ServiceRegistry/Release/Version/Persister/JanusVersionPersister.php"
    post-release-actions:
      - src/Janus/ServiceRegistry/Release/Action/BuildArchiveAction.php

# BRANCH SPECIFIC CONFIG
#  On master, we override the general config
master:
    version-generator: semantic # More complex versionning (semantic)
    version-persister:
        vcs-tag:
            tag-prefix: ''         # No more prefix for tags
    pre-release-actions:
        changelog-update:          # Update a CHANGELOG file before the release
            format: semantic
        vcs-commit: ~              # Commit the CHANGELOG