language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script: composer install -n

# @todo: enable when SSP autoloading issue is fixed
#script: phpunit --coverage-text tests/
script: phpunit -c app

notifications:
  email:
    - lucas@vanlierop.org