language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - sudo apt-get install php5-openssl php5-mcrypt
    - composer install -n --prefer-source

script: phpunit -c app

notifications:
  email:
    - janus-ssp-dev@googlegroups.com
