language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
# Disabled for now since it already failed on composer install with message: "type 5 is not implemented yet"
#  - hhvm

before_script: composer install -n

script: phpunit -c app

notifications:
  email:
    - lucas@vanlierop.org