imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
      - JanusServiceRegistryBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

        types:
            # A collection of custom types
            # Example
            janusBoolean:
                class:                Janus\ServiceRegistry\Doctrine\Type\JanusBooleanType
                commented:            true
            janusIp:
                class:                Janus\ServiceRegistry\Doctrine\Type\JanusIpType
                commented:            true
            janusDateTime:
                class:                Janus\ServiceRegistry\Doctrine\Type\JanusDateTimeType
                commented:            true
            janusUserType:
                class:                Janus\ServiceRegistry\Doctrine\Type\JanusUserTypeType
                commented:            true

        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        # Explicitely map Janus entities
        mappings:
            janus:
                type: annotation
                prefix: Janus\ServiceRegistry\Entity
                dir: "%kernel.root_dir%/../src/Janus/ServiceRegistry/Entity"
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: false }

fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    body_converter:
        enabled: true


nelmio_api_doc: ~

fos_oauth_server:
    db_driver: orm
    client_class:        Janus\ServiceRegistry\Entity\Client
    access_token_class:  Janus\ServiceRegistry\Entity\AccessToken
    refresh_token_class: Janus\ServiceRegistry\Entity\RefreshToken
    auth_code_class:     Janus\ServiceRegistry\Entity\AuthCode

