parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: janus_migrations_test
    database_user: root
    database_password: c0n3xt
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: janus
    oauth2_auth_server_url: https://apis.demo.openconext.org/
    oauth2_auth_key: csa
    oauth2_auth_secret: csa-secret
    oauth2_auth_access_token: ca2b078e-3316-4bf9-8f46-26ed2fb8ca18
    oauth2_allow_selfsign_cert: true