janus_security:
    resource: "@JanusSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

janus_connection:
    type:     rest
    prefix:   /api
    resource: "@JanusServiceRegistryBundle/Controller/ConnectionController.php"

janus_user:
    type:     rest
    prefix:   /api
    resource: "@JanusServiceRegistryBundle/Controller/UserController.php"

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
