janus_connection:
    type:     rest
    prefix:   /api
    resource: "@JanusConnectionsBundle/Controller/ConnectionController.php"

janus_user:
    type:     rest
    prefix:   /api
    resource: "@JanusUserBundle/Controller/UserController.php"

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
