# @todo fix conflicting routing for gui and rest api (only one of them work -> the last defined)
# Prefably fix this by removing FOS Rest stuff
JanusServiceRegistryGuiBundle:
  resource: @JanusServiceRegistryGuiBundle/Resources/config/routing.yml
  prefix: /

JanusServiceRegistryRestApiBundle:
  resource: @JanusServiceRegistryRestApiBundle/Resources/config/routing.yml
  prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

