janus_security:
    resource: "@JanusSecurityBundle/Controller/"
    type:     annotation
    prefix:   /


JanusServiceRegistryBundle:
  resource: @JanusServiceRegistryBundle/Resources/config/routing.yml
  prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
