security:
    access_control:
        - { path: ^/api2, roles: ROLE_ACTIONS }

    providers:
        api:
          id: resource.server.security.authentication.provider

    firewalls:
        api_secured:
            pattern:   /api2/.*
            stateless: true
            oauth2: true

