security:
    access_control:
        - { path: ^/api, roles: ROLE_ACTIONS }

    providers:
        api:
          id: resource.server.security.authentication.provider

    firewalls:
        api_secured:
            pattern:   /api/.*
            stateless: true
            oauth2: true

