services:
  authentication_provider:
    class: Janus\ServiceRegistry\Bundle\SSPIntegrationBundle\DependencyInjection\AuthenticationProvider
    arguments: [@janus_config]

  janus_config:
    class: SimpleSAML_Configuration
    factory_service: janus_config_factory
    factory_method: create

  janus_config_factory:
      class: Janus\ServiceRegistry\Bundle\SSPIntegrationBundle\DependencyInjection\SSPConfigFactory
      arguments:    ["%kernel.environment%"]

  ssp_config:
    class: SimpleSAML_Configuration
    factory_class: SimpleSAML_Configuration
    factory_method: getInstance
    lazy: true

  memcache:
    class: Memcache
    factory_class: Janus\ServiceRegistry\Bundle\SSPIntegrationBundle\DependencyInjection\MemcacheFactory
    factory_method: create
    arguments: [%memcache.server_groups%]
